### PR TITLE
Stop «Exchange assets» tab from breaking without liability proof generated && remove redundant AssetsController#partial_tree (closes #723)

### LINKED ISSUE #723: AssetsController #partial_tree is broken
I'm not sure we still use this route
Probably the solution is ```@json      = account.partial_trees.last.to_json.html_safe```
deepinscreenshot_select-area_20180322135335

### PR DESCRIPTION
**Pull request by ysv**

### CODE REVIEW

File: app/controllers/private/assets_controller.rb [hunk 1]
```diff
@@ -12,14 +12,5 @@ def index
         end
       end
     end
-
-    def partial_tree
```
Comment (yivo) [inline app/controllers/private/assets_controller.rb:16]: Why routes still has this?

image

File: app/views/private/assets/_coin_assets.html.erb [hunk 2]
```diff
@@ -14,14 +14,15 @@
             <div class="col-xs-offset-4 col-xs-16">
               <span class="pull-left"><%= t('.total', translation_data) %></span>
               <span class="pull-right">
-                <%= coin_proof.asset_sum %>
+                <%= coin_proof.present? ? coin_proof.sum : t('private.assets.liability-proof-generating') %>
```
Comment (yivo) [inline app/views/private/assets/_coin_assets.html.erb]: @yssavchuk We use underscore case for naming. Also please fix English: `liability proof is being generated`.

File: config/locales/server.en.yml [hunk 3]
```diff
@@ -457,6 +457,7 @@ en:
         total: 'Total %{currency} Assets'
       partial_tree:
         success: 'Success! Verification data generated at: %{timestamp}'
+      liability-proof-generating: Proof of Liability generation in process.
```
Comment (yivo) [inline config/locales/server.en.yml]: @yssavchuk Where is the verb in this sentence?

File: app/views/private/assets/_coin_assets.html.erb [hunk 4]
```diff
@@ -14,14 +14,15 @@
...
               </span>
             </div>
           </div>
-          <div class="clearfix"></div>
-          <div class="row">
-            <table class="table">
-              <thead>
+          <% unless coin_proof.blank? || coin_proof.addresses.empty? %>
```
Comment (yivo) [inline app/views/private/assets/_coin_assets.html.erb]: @yssavchuk I don't understand this condition. Please, rewrite without `unless`.

**Review by yivo — CHANGES_REQUESTED** [review]
@yssavchuk I also need screenshot for this page after the changes.

Please, update commit message after the changes: `Remove redundant AssetsController#partial_tree. Stop «Exchange assets» tab from breaking without liability proof generated (closes #723).`.

File: config/locales/server.en.yml (hunk 3 above)
Comment (yivo) [reply config/locales/server.en.yml]: We need `is` before `in`.

**Review by yivo — APPROVED** [review]
