### PR TITLE
Admin Deposit & Withdraw controllers fix inheritance problems (closes  #609)

### LINKED ISSUE #609: When viewing details of withdrawal i get the following error
http://peatio:8000/admin/withdraws/satoshis/2
undefined method `find_withdraw' for #<Admin::Withdraws::SatoshisController:0x00007ff4a82e9088>
      @app.call(env)

Can be fixed by making mehtond find_wihdraw public (not sure if this proper fix thought)

### PR DESCRIPTION
**Pull request by ysv**

### CODE REVIEW

File: app/controllers/admin/withdraws/banks_controller.rb [hunk 1]
```diff
@@ -28,6 +28,11 @@ def destroy
         @bank.reject!
         redirect_to :back, notice: 'Withdraw successfully destroyed!'
       end
+
+      protected
+      def find_withdraw
```
Comment (yivo) [inline app/controllers/admin/withdraws/banks_controller.rb]: @yssavchuk Pls find a way to not duplicate this.

File: app/controllers/admin/deposits/banks_controller.rb [hunk 2]
```diff
@@ -1,6 +1,6 @@
 module Admin
   module Deposits
-    class BanksController < ::Admin::Deposits::BaseController
+    class BanksController < DepositsBaseController
```
Comment (yivo) [inline app/controllers/admin/deposits/banks_controller.rb]: @yssavchuk I don't like duplicate `Deposits` and `Withdraws` name.

**Review by yivo — CHANGES_REQUESTED** [review]

**Review by yivo — APPROVED** [review]
